### ISSUE TITLE
fork of fftw/fftw3

### ISSUE THREAD

**Issue by zerothi** [amd/amd-fftw#5]
Why isn't this a fork of https://github.com/FFTW/fftw3?

It seems to me that this is simply build on top of fftw3, so why not ensure you can easily track changes?

Could you clarify the intents of this code?
I.e. will you continue to have this code orthogonal to original fftw? Or will you try and return developments to fftw?

**Comment by dvzrv** [comment]
Hi! I package fftw for Arch Linux.

As a soon-to-be AMD Ryzen 3900 user I would be very interested in these optimizations, especially in the context of [pro-audio packages, that rely on fftw](https://www.archlinux.org/packages/extra/x86_64/fftw/).

To be able to package these optimizations they have to be integrated in the upstream fftw though (otherwise they will very likely not be distributed in any official repositories of any of the current Linux/BSD distributions).

@BiplabRaut @pradeeptrgit As you have been working on this project can you give an update/ timeline in regards to when/ how you plan to do this? Fixes such as these would be very much welcome upstream I think, as long as this would not lead to an either/or optimization build.

**Comment by BiplabRaut** [comment]
Dear David and Nick,

>                                   

Thank you for your interest and queries.
We definitely intend to upstream our optimized amd-fftw to FFTW/fftw3.
We are working towards it right now and it would be done in near future.

Thanks,
S. Biplab Raut

**Comment by BiplabRaut** [comment]
Closing this issue for now.
Please feel free to contact us for any other issue/query.
